spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dealDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  kafka:
    producer:

      bootstrap-servers: "127.0.0.1:9092"
      client-id: "neoflex-producer"
  liquibase:
    change-log: liquibase/changelog.yml

server:
  port: 8081

feign:
  client:
    server: http://localhost:8080/conveyor

kafka:
  topic1: "finish-registration"
  topic2: "create-documents"
  topic3: "send-documents"
  topic4: "send-ses"
  topic5: "credit-issued"
  topic6: "application-denied"



