spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: a@gmail.com
    password: "aaa"
    properties.mail.smtp:
      auth: true
      starttls.enable: true
#    test-connection: true
  kafka:
    consumer:
      group-id: "neoflex-group"
      bootstrap-servers: "127.0.0.1:9092"
      client-id: "neoflex-consumer"
      properties:
        spring.json.trusted.packages: "ru.dolya.dossier.*"

server:
  port: 8083

feign:
  client:
    server: http://localhost:8081/deal

kafka:
  topic1: "finish-registration"
  topic2: "create-documents"
  topic3: "send-documents"
  topic4: "send-ses"
  topic5: "credit-issued"
  topic6: "application-denied"
